### ISSUE TITLE
Generate with NonEmpty if minItems: 1

### ISSUE THREAD

**Issue by pbrisbin** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#101]
When I generate a spec from a Haskell server using `NonEmpty`, it adds `minItems: 1`:

```json
          "levels": {
            "items": {
              "$ref": "#/components/schemas/ElaArticleLevel"
            },
            "minItems": 1,
            "type": "array"
          },
```

Ideally the generator should generate a `NonEmpty ElaArticleLevel` instead of `[ElaArticleLevel]` when it sees this. Currently, I have a bunch of `NE.fromList` conversions, with comments that's it's actually safe because the spec says `minItems: 1` -- but that's only true right now, and could change going forward.

Hard to say what something like `minItems: 2` (for example) should do. I'd be inclined to just say `NonEmpty` for any `minItems: x | x > 0` as a good 80/20 vs getting fancier.

**Comment by pbrisbin** [comment]
I'm bumping in a few of these sorts of conversions, such as using `Natural` when `minimum: 0` or `UUID` when `format: uuid`. But I will wait for your thoughts on this one before proceeding to make more Issues.

**Comment by NorfairKing** [comment]
I like this idea!

**Comment by joel-bach** [comment]
I like this idea as well! I am not sure if I get to do an implementation of this in the near future myself, so if you want to give it a try, feel free to open a PR 🙏

**Comment by pbrisbin** [comment]
Great, I've got a draft PR for `NonEmpty` here: https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/pull/102

Happy to poke at the other stuff I mentioned after that lands.

**Comment by joel-bach** [comment]
Hey @pbrisbin, with #102 being merged, do we want to close this issue?

**Comment by joel-bach** [comment]
I think we could also just discuss these in a respective PR, wdyt? But I am also fine with leaving this one open to keep track on them.
