### ISSUE TITLE
Cannot generate client library for a webdriver spec.

### ISSUE THREAD

**Issue by NorfairKing** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#52]
I'm trying to generate a client library for this spec: https://github.com/NorfairKing/selenium-openapi/blob/bool/selenium.yaml 

I'm getting (at least) two problems: 

A missing import:
![text](https://user-images.githubusercontent.com/3521180/125634079-0471c1f6-b529-475f-b572-e213764b656f.png)

Not enough qualification
![duplicate](https://user-images.githubusercontent.com/3521180/125634040-6d7c3a41-972e-478f-af22-381b2ec29546.png)

**Comment by NorfairKing** [comment]
I've pushed my attempt to https://github.com/NorfairKing/webdriver-client
You can try running `./scripts/generate-webdriver-api.sh` there to reproduce.

**Comment by joelfisch** [comment]
The first problem is fixed by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/pull/53.
