### ISSUE TITLE
Handling "required", but "nullable: true"

### ISSUE THREAD

**Issue by saurabhnanda** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#55]
I'm trying to generate an API client for Hetzner's API (spec at https://docs.hetzner.cloud/spec.json ) and it has this strangeness where a property is **required, but allowed to be nullable**. This is causing almost all parsing of responses to fail, because the generated data-type is not a `Maybe a`, but simply `a`

At first I thought that the spec itself was broken, but apparently this is [something that is to be expected in OpenAPI specs](https://stackoverflow.com/questions/45575493/what-does-required-in-openapi-really-mean)

How can this be handled in the code generator?

**Comment by sorki** [comment]
I've managed to hit this as well and came up with a patch, feel free to use / open a PR with if it helps.

https://github.com/sorki/Haskell-OpenAPI-Client-Code-Generator/commit/5d1ecf53bc6b9e44eaeab3b9df2ee4a1d7264df0

**Comment by saurabhnanda** [comment]
@sorki brilliant - thanks! Will cherry-pick your commit on the latest version of this package and try. Any reason for not raising a PR upstream?

**Comment by sorki** [comment]
Time :-) I've managed to get my generated API working with this patch but then decided I'll go `servant` route instead. It also felt a little obscure but it seems I'm not the only one having this problem.

**Comment by saurabhnanda** [comment]
@sorki what's the `servant` route? What's the alternative to this package to generate a haskell client from openapi spec? I tried https://openapi-generator.tech/docs/generators/haskell-http-client but it generate everything in just two modules, which take forever to compile!

**Comment by sorki** [comment]
> @sorki what's the `servant` route? What's the alternative to this package to generate a haskell client from openapi spec? I tried https://openapi-generator.tech/docs/generators/haskell-http-client but it generate everything in just two modules, which take forever to compile!

Using `servant` to describe the API manually and then creating a client using the decription, instead of generating it. More tedious but the result can be better, depending on the target API.

**Comment by saurabhnanda** [comment]
Okay - I think the issue has another aspect. 

- when the server sends back a response, the field may be `null`
- however, when making the request, either the field may be absent from the JSON, or if it is present it _should not_ be `null`

How do I handle this?

**Comment by joelfisch** [comment]
Hi @saurabhnanda ,
Thank you for rising this issue! I currently see no downside to @sorki 's implementation for handling the response from the server and will try to integrate it later this week.
As to sending requests: I think ideally the generated client code should handle `required` and `nullable` in the `ToJSON` instance as follows:
- `required` and `nullable: true`: `Nothing` is serialised to `null`
- `required` and `nullable: false`: `Nothing` should omit the property
- not `required` and `nullable: true`: `Nothing` should omit the property

The third case is ambiguous and can lead to problems if a server implementation relies on the distinction between null and omitting the property (btw the same is true for the response handling as the absence of a property and a `null` value cannot be distinguished by the proposed implementation). But I think it is worth it to handle it like this to simplify the interface. What do you think @saurabhnanda ?

**Comment by saurabhnanda** [comment]
@joelfisch my thoughts on this topic:

For my current use-case it _seems_ like the proposed solution _could work while encoding/sending the JSON. However, it _might_ break for some other API/server, because of the inherent ambiguity in the way the spec has been written. 

Similarly, while receiving, I don't think we can use `Maybe a` to distinguish between these three scenarios. We will need something like `data OptionalJsonValue a = Absent | Null | Present a` or a `Maybe (Maybe a)`

- key & value present: `Present a` OR `Just (Just a)`
- key absent: `Absent` OR `Nothing`
- key present, but value = null: `Null` OR `Just Nothing`

Is it worth it to make both of these behaviours configurable using one of the two approaches:
- User can pick between `Maybe a`, `Maybe (Maybe a))`, and `OptionalJsonValue a`
- Or, during the code-gen can we accept an optional Haskell file containing a module with two functions: (or type-class instances): (a) one to decode an optional JSON value into a data-type of the user's choice, and (b) one to encode an optional JSON value into a data-type of the user's choice.

Since, I'm stuck with this problem right now, I might be able to take a stab at solving this problem if you could help me with where I should start reading the code from.

**Comment by joelfisch** [comment]
I think an additional ADT would be pretty neat but what I do not like is that it really only works for properties of objects (as only in this combination `nullable` and `required` can be used). Therefore I would propose that for schemas with `nullable: true` the type has to be wrapped in a `Maybe`. In the case of an optional property you would get your proposed `Maybe (Maybe a)`.
I think the main challenge is that you would have to create a non-nullable type and then a type alias, e. g.:

```haskell
type X = Maybe XNonNullable
data XNonNullable = XNonNullable { propX :: Text, propY :: Text }
```

This is necessary to remove the need that referencing placing need to know about the nullability. It would probably make sense to create a newtype and adjust the `ToJSON` instance to ensure it is serialized to `null`. What do you think?

As to an entry point: I would suggest looking at `Model.hs` (e. g. https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/blob/master/openapi3-code-generator/src/OpenAPI/Generate/Model.hs#L179) where all the model generation is done.

**Comment by joelfisch** [comment]
Hey there, thank you for your input! I really like this approach but there is one flaw in my opinion which is that `nullable` is possible on every schema whereas optional properties is only part of `type: object`. This led me to the conclusion that two more or less separate solutions would be the more generic approach to implement it. I created a PR https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/pull/75 which aims to add support for `nullable` and also fix  serialization (thanks to @s9gf4ult for the idea in https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/pull/73) / deserialization of optional fields (omitting them instead of turning to null values and do not parse null as empty fields).

I will merge this PR soon, please shout if you think there is something missing/wrong about the approach. I will close this issue afterwards as I believe it is solved with it (let me know if you think I am wrong about this).

**Comment by stepcut** [comment]
I am happy with any solution that works.

For schemas that do not allow `optional` then with the `Property`  type would always be `Property Required nullable`. However, if it is fairly common that a value is required and non-nullable, then you have the extra overhead of constructing and matching on the `Present` constructor when a simple value would due just fine.

It was fun to implement the above code, but I do have questions about how much tedium it would add compared to other approaches.
