### ISSUE TITLE
StripeT/StripeM in generated code?

### ISSUE THREAD

**Issue by saurabhnanda** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#57]
Did something wrong get merged into the `master` branch? All generated code seems to be referring to `StripeT` and `StripeM`

**Comment by saurabhnanda** [comment]
Please see if https://github.com/saurabhnanda/Haskell-OpenAPI-Client-Code-Generator/commit/c977d8f7bdec24c7bead1908e937870363ffb431 fixes the problem.

**Comment by joelfisch** [comment]
Thank you for pointing this out, I created the following PR to address it: https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/pull/59
