### ISSUE TITLE
Name Clash - Binance API

### ISSUE THREAD

**Issue by DavidEichmann** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#61]
My understanding of OpenAPI is poor so forgive me for my lack of characterization.
I'm running the code generator on the binance api: https://github.com/binance/binance-api-swagger/blob/master/spot_api.yaml. It seems there are name clashes for schemas of array type and their elements:

```haskell
--
-- src/StripeAPI/Types/SavingsFixedActivityRedemptionRecord.hs
--

data SavingsFixedActivityRedemptionRecord = SavingsFixedActivityRedemptionRecord { ... }

-- | Defines an alias for the schema located at @components.schemas.savingsFixedActivityRedemptionRecord@ in the specification.
-- 
-- 
type SavingsFixedActivityRedemptionRecord = [SavingsFixedActivityRedemptionRecord]
```

As far as I tried I can't fix this with CLI options. Is this a bug? Any help would be appreciated.

**Comment by NorfairKing** [comment]
@joelfisch  May be able to help with this

**Comment by joelfisch** [comment]
Hi @DavidEichmann,

You are right, this is a bug in the generator. I created a PR to fix this: https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/pull/62

Note that you will encounter another problem with the specification you are using as there is a schema called `aggTrade` which has two members which only differ in casing. This is something we currently do not support but you can get around it by using the CLI option `--opaque-schema` to exclude the properties from generation (e. g. `--opaque-schema="aggTrade"`). This will result in a type alias to `Data.Aeson.Value` being generated for aggTrade which you then can query using the `aeson` package.

Does this work for you?

**Comment by DavidEichmann** [comment]
I'm just getting started with the API, so hopefuly I can get by without `aggTrade`.

@joelfisch Thanks for the speedy fix!
