### ISSUE TITLE
Support for aeson-2.0 

### ISSUE THREAD

**Issue by s9gf4ult** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#77]
There are [new incompatibilities](https://hackage.haskell.org/package/aeson-2.0.3.0/changelog) in `aeson-2.0.0.0`.

Particularly, the `KeyMap` which is [used](https://hackage.haskell.org/package/aeson-2.0.3.0/docs/Data-Aeson.html#t:Object) instead of `Map Text Value` in `Object` constructor. 

The code generated does not compile with `aeson-2` and later.

**Comment by NorfairKing** [comment]
@joelfisch ^ This is the issue that I ran into as well.

**Comment by joelfisch** [comment]
Closing this since I have tests in CI testing it with Aeson 2.0. Please reopen it or create a new issue if it does not work for you or I missed something.
