### ISSUE TITLE
Improve operation interface

### ISSUE THREAD

**Issue by joelfisch** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#9]
Currently, there are four different functions which can be used to execute an operation (explicit configuration, explicit configuration with raw response body, monadic and monadic with raw response body). The default should be a monadic version using a new monad which can run IO operations and contains the configuration.

Additionally, the return type of operation functions should not be of type `Either` as the user has to catch exceptions anyway.

**Comment by joelfisch** [comment]
@NorfairKing I have a question regarding the implementation:

We talked about creating a type class `MonadStripe` but I do not remember what this class would contain in terms of functionality. Is it really necessary?
My current proposition would look something like this:

```haskell
newtype StripeT m a = StripeT (MR.ReaderT Configuration m a)
  deriving (Functor, Applicative, Monad, MR.MonadReader Configuration)

instance MT.MonadTrans StripeT where
  lift = StripeT . MT.lift

instance MonadHTTP m => MonadHTTP (StripeT m) where
  httpBS = MT.lift . httpBS

type StripeM a = StripeT IO a

runWithConfiguration :: Configuration -> StripeT m a -> m a
runWithConfiguration c (StripeT r) = MR.runReaderT r c
```

Another question is regarding the `SecurityScheme`. We talked about removing the type class and it turns out that this would be quite easy. But it would result in the `Configuration` record containing a function. Now is my question: How bad is it if a record contains a function? If we would do it like this, we could drop all the `SecurityScheme` constraints everywhere. What do you think?

**Comment by NorfairKing** [comment]
I suggest we focus on simplicity for now.

I suggest getting rid of `StripeT` and define `StripeM` directly:

```
newtype StripeM a = StripeT (ReaderT Configuration IO a)
```

about whether records can contain a function: it depends on whether you want to be able to print the function. In the case of configuration: you don't want to print it anyway because it contains secrets.

Does that answer your question.

**Comment by joelfisch** [comment]
Yes, this answers my question, thank you. As for `StripeT`: We currently need a way to replace the IO monad with a mock monad for the level 2 system tests. As you mentioned, you are not a fan of mocking anyway but for now I think it is the easiest way to leave the level 2 tests as they are. Maybe we can talk about other ways of testing the second level integration sometime.

Is it ok with you if I leave `StripeT` as it is and you can just use the type alias `StripeM` for now? With this solution we could remove `StripeT` in the future without breaking `StripeM`, right?

**Comment by NorfairKing** [comment]
I'm fine with the alias for now, but we should get rid of the mocking that you have so that we can get a simpler interface here.

**Comment by joelfisch** [comment]
> I'm fine with the alias for now, but we should get rid of the mocking that you have so that we can get a simpler interface here.

I created an issue here: https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/issues/21
> 
> > Is it ok with you if I leave StripeT as it is and you can just use the type alias StripeM for now? With this solution we could remove StripeT in the future without breaking StripeM, right?
> 
> Not really, but no one is using this yet anyway.

Fair enough.
