### ISSUE TITLE
Issue with HMRC's VAT API

### ISSUE THREAD

**Issue by locallycompact** [Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator#94]
Trying to use this tool to convert the specification here: https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0/oas/page

Results:
![vat](https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/assets/1267527/5384e5b2-ba7b-407f-bd46-cc74cee3f5ae)

![vat2](https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/assets/1267527/b773dbba-3328-44c1-9c2c-4458c6ce5dd2)

**Comment by locallycompact** [comment]
@NorfairKing any hints?

**Comment by NorfairKing** [comment]
@joel-bach I guess `multipleOf` doesn't allow for non-integer values. Is that according to spec?

**Comment by joel-bach** [comment]
I had a look at the [spec](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.1) which does only mention this to be a number greater than zero. Therefore I think the presented specification is indeed valid and it is a parsing problem on our side. Considering that the code generator does not do anything with that value, I am in favor of changing it to allow floating point numbers as well. I'll have a look tomorrow.

**Comment by joel-bach** [comment]
Hey @locallycompact , this should be fixed by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator/pull/95 which has been merged to master. I'll close this issue as I am confident with the fix but please let me know if it does not work for some reason 🙏
